// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bccdcbzdrwlmzholhdth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjY2RjYnpkcndsbXpob2xoZHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4ODkyNTEsImV4cCI6MjA4MzQ2NTI1MX0.mqNHlBTBmyH8xAzhn1M8XX9ctaQaIu0tkPDtxLONfq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});